import assert from "node:assert/strict";
import { access, readFile, readdir } from "node:fs/promises";
import test from "node:test";

test("native Next.js build creates the Vercel output", async () => {
  await access(new URL("../.next/BUILD_ID", import.meta.url));
  const packageSource = await readFile(new URL("../package.json", import.meta.url), "utf8");
  const vercelSource = await readFile(new URL("../vercel.json", import.meta.url), "utf8");
  assert.match(packageSource, /"build": "next build"/);
  assert.match(vercelSource, /"framework": "nextjs"/);
});

test("legacy customer links also open support without authentication", async () => {
  const publicSource = await readFile(new URL("../app/PublicSupport.tsx", import.meta.url), "utf8");
  const layoutSource = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const customerSource = await readFile(new URL("../app/customer/page.tsx", import.meta.url), "utf8");
  const passwordSource = await readFile(new URL("../app/set-password/page.tsx", import.meta.url), "utf8");
  assert.match(layoutSource, /LordsCare Bot Support/);
  assert.match(publicSource, /Simple plans\. Direct support/);
  assert.match(publicSource, /Already subscribed\? Browse the command guide/);
  assert.match(customerSource, /PublicSupport/);
  assert.match(passwordSource, /PublicSupport/);
  assert.doesNotMatch(customerSource + passwordSource, /LoginPanel|Choose your password|Checking your secure link/i);
});

test("customer settings retain applied state and serialize disabled switches", async () => {
  const source = await readFile(new URL("../app/PortalShell.tsx", import.meta.url), "utf8");
  assert.match(source, /request\.status === "applied"/);
  assert.match(source, /Current applied values loaded/);
  assert.match(source, /element\.type === "checkbox"/);
  assert.match(source, /settings\[element\.name\] = "off"/);
  assert.match(source, /appliedChecked\("always_shielded"/);
  assert.match(source, /appliedValue\("shield_redeploy_minutes"/);
});

test("customer bank commands use the administrator-configured prefix", async () => {
  const portalSource = await readFile(new URL("../app/PortalShell.tsx", import.meta.url), "utf8");
  const source = await readFile(new URL("../app/CommandLibrary.tsx", import.meta.url), "utf8");
  const homeSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const commandSource = await readFile(new URL("../app/data.ts", import.meta.url), "utf8");
  const migration = await readFile(new URL("../supabase/migrations/002_customer_command_prefix.sql", import.meta.url), "utf8");
  assert.match(portalSource, /commandPrefix: profile\?\.command_prefix \|\| "!"/);
  assert.match(portalSource, /<CommandLibrary prefix=\{snapshot\?\.commandPrefix \|\| "!"\}/);
  assert.match(source, /Commands for prefix <code>\{prefix\}<\/code>/);
  assert.match(source, /command\.replaceAll\("!", prefix\)/);
  assert.match(portalSource, /customer_command_prefix_updated/);
  assert.match(homeSource, /PublicSupport/);
  assert.doesNotMatch(homeSource, /LoginPanel/);
  assert.equal((commandSource.match(/^  \{ command:/gm) ?? []).length, 67);
  assert.match(commandSource, /!relocatekvk \[K\]/);
  assert.match(commandSource, /!findnestlocal \[level\]/);
  assert.match(commandSource, /!adminrss \[F\] \[S\] \[W\] \[O\] \[G\] \[player\]/);
  assert.doesNotMatch(commandSource, /relocator/);
  assert.match(migration, /default '!'/);
  assert.match(migration, /between 1 and 3/);
});

test("public guided setup request covers the core bot configuration", async () => {
  const publicSource = await readFile(new URL("../app/PublicSupport.tsx", import.meta.url), "utf8");
  const routeSource = await readFile(new URL("../app/setup-request/page.tsx", import.meta.url), "utf8");
  const builderSource = await readFile(new URL("../app/SetupRequestBuilder.tsx", import.meta.url), "utf8");
  const settingsSource = await readFile(new URL("../app/setupSettings.ts", import.meta.url), "utf8");
  assert.doesNotMatch(publicSource, /\/setup-request|Create full setup|Configure every part of your bot/);
  assert.match(routeSource, /redirect\("\/"\)/);
  assert.equal((settingsSource.match(/id: "/g) ?? []).length, 8);
  assert.match(settingsSource, /Daily tasks and guild activity/);
  assert.match(settingsSource, /Protection preferences/);
  assert.match(settingsSource, /Resource gathering/);
  assert.match(settingsSource, /Monster hunting/);
  assert.match(settingsSource, /Darknest rallies/);
  assert.match(settingsSource, /Buildings, research, and army/);
  assert.match(settingsSource, /Heroes and familiars/);
  assert.match(settingsSource, /Events, Guild Fest, and artifacts/);
  assert.match(settingsSource, /Vergeway daily collection/);
  assert.match(settingsSource, /Total Infantry target/);
  assert.match(builderSource, /navigator\.clipboard\.writeText/);
  assert.match(builderSource, /navigator\.share/);
  assert.match(builderSource, /Never enter a game password, OTP, login token, or access key/);
});

test("public events section includes the Guild Duel guide", async () => {
  const publicSource = await readFile(new URL("../app/PublicSupport.tsx", import.meta.url), "utf8");
  const eventSource = await readFile(new URL("../app/events/page.tsx", import.meta.url), "utf8");
  assert.match(publicSource, /href="\/events"/);
  assert.match(eventSource, /Guild Duel/);
  assert.match(eventSource, /Familiar Growth/);
  assert.match(eventSource, /Research Racer/);
  assert.match(eventSource, /Hero Coach/);
  assert.match(eventSource, /Artifact Resurgence/);
  assert.match(eventSource, /Comprehensive Development/);
  assert.match(eventSource, /240K/);
  assert.equal((eventSource.match(/day: \d/g) ?? []).length, 5);
  assert.match(eventSource, /Use 1 Gold Blazing Ember/);
  assert.match(eventSource, /Win 1 Hero Colosseum battle/);
  assert.match(eventSource, /Use 1 Legendary Record/);
  assert.match(eventSource, /Use 1 Army Star Scroll/);
  assert.doesNotMatch(eventSource, /guild-duel-day-1\.jpg|from "next\/image"/);
});

test("events section includes the Guild Showdown rank tactic", async () => {
  const eventSource = await readFile(new URL("../app/events/page.tsx", import.meta.url), "utf8");
  assert.match(eventSource, /id="guild-showdown"/);
  assert.match(eventSource, /href="#guild-showdown"/);
  assert.match(eventSource, /Guild Board → Might Ranking → Your Rank/);
  assert.match(eventSource, /cavalry: \[1, 4, 7, 10/);
  assert.match(eventSource, /ranged: \[2, 5, 8, 11/);
  assert.match(eventSource, /infantry: \[3, 6, 9, 12/);
  assert.match(eventSource, /Do not send mixed troops unless you are the rally lead/);
  assert.match(eventSource, /Fury, Prison, and Altar boosts/);
  assert.match(eventSource, /50% Army ATK boost/);
  assert.match(eventSource, /Guild Showdown actions do not activate Battle Fury by themselves/);
  assert.match(eventSource, /lordsmobile\.fandom\.com\/wiki\/Guild_Showdown/);
});

test("responsive layout covers phones, tablets, drawers, tables, and dialogs", async () => {
  const publicSource = await readFile(new URL("../app/PublicSupport.tsx", import.meta.url), "utf8");
  const portalSource = await readFile(new URL("../app/PortalShell.tsx", import.meta.url), "utf8");
  const headerSource = await readFile(new URL("../app/SupportHeader.tsx", import.meta.url), "utf8");
  const cssSource = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(publicSource, /id="commands"/);
  assert.match(headerSource, /label: "Events", href: "\/events"/);
  assert.match(headerSource, /label: "Monsters", href: "\/monsters"/);
  assert.match(portalSource, /mobile-nav-backdrop/);
  assert.match(portalSource, /aria-expanded=\{mobileOpen\}/);
  assert.match(portalSource, /data-label="Customer"/);
  assert.match(portalSource, /data-label="Actions"/);
  assert.match(cssSource, /@media \(max-width: 1023px\)/);
  assert.match(cssSource, /@media \(max-width: 767px\)/);
  assert.match(cssSource, /@media \(max-width: 479px\)/);
  assert.match(cssSource, /env\(safe-area-inset-bottom\)/);
  assert.match(cssSource, /\.support-nav nav a\.mobile-primary-link \{ display: inline-flex; \}/);
  assert.match(cssSource, /\.support-nav nav a\.nav-external-link \{ display: none; \}/);
  assert.match(cssSource, /\.customer-table td::before/);
  assert.match(cssSource, /\.modal-card, \.plan-modal, \.accounts-modal \{[^}]*border-radius: 20px 20px 0 0/s);
});

test("private admin subscription register tracks customers, plans, accounts and renewals", async () => {
  const portalSource = await readFile(new URL("../app/PortalShell.tsx", import.meta.url), "utf8");
  const loginSource = await readFile(new URL("../app/admin-login/page.tsx", import.meta.url), "utf8");
  const loginPanelSource = await readFile(new URL("../app/LoginPanel.tsx", import.meta.url), "utf8");
  const publicHeaderSource = await readFile(new URL("../app/SupportHeader.tsx", import.meta.url), "utf8");
  const supabaseSource = await readFile(new URL("../lib/supabase.ts", import.meta.url), "utf8");
  const publicConfigSource = await readFile(new URL("../lib/public-supabase-config.ts", import.meta.url), "utf8");
  const ledgerMigration = await readFile(new URL("../supabase/migrations/003_internal_customer_ledger.sql", import.meta.url), "utf8");
  const removeRouteSource = await readFile(new URL("../app/api/admin/customers/remove/route.ts", import.meta.url), "utf8");
  assert.match(portalSource, /Total subscribers/);
  assert.match(portalSource, /Active subscriptions/);
  assert.match(portalSource, /Managed accounts/);
  assert.match(portalSource, /Renewals due/);
  assert.match(portalSource, /Subscription register/);
  assert.match(portalSource, /All statuses/);
  assert.match(portalSource, /Manage renewal/);
  assert.match(portalSource, /Change password/);
  assert.match(portalSource, /signInWithPassword\(\{ email, password: currentPassword \}\)/);
  assert.match(portalSource, /updateUser\(\{ password: newPassword \}\)/);
  assert.match(portalSource, /newPassword\.length < 12/);
  assert.match(portalSource, /window\.location\.href = "\/admin-login"/);
  assert.match(portalSource, /Private business record/);
  assert.match(portalSource, /No invitation email will be sent/);
  assert.match(portalSource, /from\("internal_customers"\)\.insert/);
  assert.match(portalSource, /ManageInternalCustomerDialog/);
  assert.match(portalSource, /Record renewal today/);
  assert.match(portalSource, /Remove customer permanently/);
  assert.match(portalSource, /Type the customer name exactly/);
  assert.match(portalSource, /fetch\("\/api\/admin\/customers\/remove"/);
  assert.doesNotMatch(portalSource, /Invite customer|Sending invitation/);
  assert.match(ledgerMigration, /create table public\.internal_customers/);
  assert.match(ledgerMigration, /admins manage internal customers/);
  assert.doesNotMatch(ledgerMigration, /auth\.users/);
  assert.match(removeRouteSource, /internal_customer_removed/);
  assert.match(removeRouteSource, /portal_customer_removed/);
  assert.match(removeRouteSource, /auth\.admin\.deleteUser/);
  assert.match(removeRouteSource, /profile\.role !== "customer"/);
  assert.match(portalSource, /role === "admin" \? "\/admin-login" : "\/"/);
  assert.match(loginSource, /robots: \{ index: false, follow: false \}/);
  assert.match(loginSource, /<LoginPanel adminOnly \/>/);
  assert.match(loginPanelSource, /does not have administrator access/);
  assert.match(supabaseSource, /publicSupabaseUrl/);
  assert.match(supabaseSource, /publicSupabaseKey/);
  assert.match(publicConfigSource, /sb_publishable_/);
  assert.doesNotMatch(publicConfigSource, /service_role|secret/i);
  assert.doesNotMatch(publicHeaderSource, /admin-login|Admin sign in/);
});

test("private business analytics tracks sales, monthly earnings, expenses, slots and profit", async () => {
  const portalSource = await readFile(new URL("../app/PortalShell.tsx", import.meta.url), "utf8");
  const analyticsSource = await readFile(new URL("../app/BusinessAnalytics.tsx", import.meta.url), "utf8");
  const analyticsMigration = await readFile(new URL("../supabase/migrations/004_business_analytics.sql", import.meta.url), "utf8");
  assert.match(portalSource, /Business analytics/);
  assert.match(portalSource, /<BusinessAnalytics \/>/);
  assert.match(analyticsSource, /Total sales collected/);
  assert.match(analyticsSource, /Bot earning this month/);
  assert.match(analyticsSource, /Overall profit \/ loss/);
  assert.match(analyticsSource, /Prepaid plans allocated monthly/);
  assert.match(analyticsSource, /Number\(item\.amount_inr\) \/ item\.service_months/);
  assert.match(analyticsSource, /purchased_extra_slots \* settings\.extra_slot_cost_inr/);
  assert.match(analyticsMigration, /monthly_bot_cost_inr integer not null default 2000/);
  assert.match(analyticsMigration, /included_slots integer not null default 7/);
  assert.match(analyticsMigration, /extra_slot_cost_inr integer not null default 780/);
  assert.match(analyticsMigration, /create table public\.business_transactions/);
  assert.match(analyticsMigration, /admins manage business transactions/);
  assert.match(analyticsMigration, /track_internal_customer_payment_trigger/);
  assert.match(analyticsMigration, /track_portal_subscription_payment_trigger/);
});

test("monster guide ships a complete local catalog and companion-tool architecture", async () => {
  const monsters = JSON.parse(await readFile(new URL("../app/monsters/monsters.json", import.meta.url), "utf8"));
  const heroes = JSON.parse(await readFile(new URL("../app/monsters/heroes.json", import.meta.url), "utf8"));
  const repositorySource = await readFile(new URL("../app/monsters/repository.ts", import.meta.url), "utf8");
  const explorerSource = await readFile(new URL("../app/monsters/MonstersExplorer.tsx", import.meta.url), "utf8");
  const detailSource = await readFile(new URL("../app/monsters/[slug]/page.tsx", import.meta.url), "utf8");
  const homeSource = await readFile(new URL("../app/PublicSupport.tsx", import.meta.url), "utf8");
  const monsterAssets = await readdir(new URL("../public/monsters/", import.meta.url));
  assert.equal(monsters.length, 43);
  assert.equal(monsterAssets.length, 43);
  assert.ok(heroes.length >= 30);
  assert.ok(monsters.every((monster) => monster.image?.startsWith("/monsters/") && monster.sourceUrl.includes("lordsmobile.fandom.com/wiki/")));
  assert.ok(monsters.filter((monster) => monster.category === "Normal").every((monster) => monster.recommendedAttackType && monster.heroLineups.length));
  assert.equal(monsters.some((monster) => ["Monster", "Monster Hunting"].includes(monster.name)), false);
  assert.equal(monsters.find((monster) => monster.name === "Gargantua")?.recommendedAttackType, "Magic");
  assert.equal(monsters.find((monster) => monster.name === "Queen Bee")?.recommendedAttackType, "Physical");
  assert.match(repositorySource, /getMonsterBySlug/);
  assert.match(repositorySource, /searchMonsters/);
  assert.match(repositorySource, /getRelatedMonsters/);
  assert.match(explorerSource, /No monsters found/);
  assert.match(explorerSource, /Clear monster search/);
  assert.match(explorerSource, /Favorite monsters/);
  assert.match(detailSource, /generateStaticParams/);
  assert.match(detailSource, /MonsterHeroLineup/);
  assert.match(detailSource, /MonsterMobileActions/);
  assert.match(homeSource, /href="\/monsters"/);
});

test("public plans turn approved prices into a direct WhatsApp enquiry", async () => {
  const planSource = await readFile(new URL("../app/plans/page.tsx", import.meta.url), "utf8");
  const conversionSource = await readFile(new URL("../app/PlanConversion.tsx", import.meta.url), "utf8");
  const contactSource = await readFile(new URL("../app/contact.ts", import.meta.url), "utf8");
  const headerSource = await readFile(new URL("../app/SupportHeader.tsx", import.meta.url), "utf8");
  const homeSource = await readFile(new URL("../app/PublicSupport.tsx", import.meta.url), "utf8");
  const dataSource = await readFile(new URL("../app/data.ts", import.meta.url), "utf8");
  const layoutSource = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  await access(new URL("../public/og.png", import.meta.url));
  assert.match(planSource, /Plans start from/);
  assert.match(planSource, /Ask on WhatsApp/);
  assert.match(conversionSource, /Send enquiry on WhatsApp/);
  assert.match(conversionSource, /Never send a password, OTP, login token, or access key/);
  assert.match(conversionSource, /window\.open\(createWhatsAppUrl\(enquiry\)/);
  assert.match(contactSource, /916238196131/);
  assert.match(contactSource, /https:\/\/wa\.me\//);
  assert.match(headerSource, /label: "Plans", href: "\/plans"/);
  assert.match(homeSource, /Plans from ₹150/);
  assert.doesNotMatch(homeSource, /What is your command prefix|aria-label="Command prefix"|prefix-card/);
  assert.match(homeSource, /<CommandLibrary prefix="!"/);
  assert.match(dataSource, /monthly: 150, quarterly: 400, yearly: 1500/);
  assert.match(layoutSource, /\/og\.png/);
});

test("public features explain the managed service without exposing infrastructure", async () => {
  const homeSource = await readFile(new URL("../app/PublicSupport.tsx", import.meta.url), "utf8");
  const pageSource = await readFile(new URL("../app/features/page.tsx", import.meta.url), "utf8");
  const gridSource = await readFile(new URL("../app/FeatureGrid.tsx", import.meta.url), "utf8");
  const dataSource = await readFile(new URL("../app/featureData.ts", import.meta.url), "utf8");
  const headerSource = await readFile(new URL("../app/SupportHeader.tsx", import.meta.url), "utf8");
  assert.match(headerSource, /label: "Features", href: "\/features"/);
  assert.match(homeSource, /What LordsCare can handle/);
  assert.match(homeSource, /Three steps to get started/);
  assert.match(pageSource, /What LordsCare can configure/);
  assert.match(pageSource, /From plan to configuration in three steps/);
  assert.match(gridSource, /customer-feature-card/);
  assert.equal((dataSource.match(/id: "/g) ?? []).length, 8);
  assert.match(dataSource, /Vergeway daily collection/);
  assert.match(dataSource, /Building upgrade priorities/);
  assert.match(dataSource, /Infantry, Ranged, and Cavalry training/);
  assert.match(dataSource, /Familiar development/);
  assert.match(dataSource, /Guild Bank commands/);
  assert.doesNotMatch(homeSource + pageSource + dataSource, /Windows|Windows Server|VPS|software installation|upstream|slot cost/i);
});
