export const commands = [
  { command: "tbal", description: "Check your resource balance", group: "Resources", admin: false },
  { command: "tfood 5M", description: "Request 5M food", group: "Resources", admin: false },
  { command: "tstone 5M", description: "Request 5M stone", group: "Resources", admin: false },
  { command: "twood 5M", description: "Request 5M wood", group: "Resources", admin: false },
  { command: "tore 5M", description: "Request 5M ore", group: "Resources", admin: false },
  { command: "tgold 5M", description: "Request 5M gold", group: "Resources", admin: false },
  { command: "trss 5M 5M 5M 5M 0", description: "Request multiple resources together", group: "Resources", admin: false },
  { command: "tpos", description: "Get the bank location", group: "Information", admin: false },
  { command: "tshield", description: "Check remaining shield time", group: "Information", admin: false },
  { command: "tstats", description: "Check your gift statistics", group: "Information", admin: false },
  { command: "tquest", description: "Check Guild Festival status", group: "Information", admin: false },
  { command: "tfindtile food 4", description: "Find a level 4 food tile", group: "Search", admin: false },
  { command: "tfindmonster hardrox 2", description: "Find a level 2 monster", group: "Search", admin: false },
  { command: "tfindnest 3", description: "Find a level 3 Darknest", group: "Search", admin: false },
  { command: "tadminbal Player", description: "Check a player's balance", group: "Bank admin", admin: true },
  { command: "tadminrss Player 5M 5M 5M 5M 0", description: "Send a full resource set administratively", group: "Bank admin", admin: true },
  { command: "trelocator", description: "Manage bank relocator actions", group: "Bank admin", admin: true },
  { command: "tmigrate", description: "Start the configured migration action", group: "Bank admin", admin: true },
  { command: "tabort", description: "Cancel pending resource shipments", group: "Bank admin", admin: true },
  { command: "trecall", description: "Recall troops", group: "Bank admin", admin: true },
];

export const planPrices = [
  { accounts: 1, monthly: 150, quarterly: 400, yearly: 1500 },
  { accounts: 2, monthly: 280, quarterly: 750, yearly: 2800 },
  { accounts: 3, monthly: 400, quarterly: 1100, yearly: 4000 },
  { accounts: 4, monthly: 500, quarterly: 1400, yearly: 5000 },
  { accounts: 5, monthly: 600, quarterly: 1700, yearly: 6000 },
];
