import Link from "next/link";
import { CalendarDays, CheckCircle2, Command, Crosshair, MessageCircle, ShieldCheck, Swords, Users } from "lucide-react";
import { CommandLibrary } from "./CommandLibrary";
import { generalWhatsAppUrl } from "./contact";
import { FeatureGrid } from "./FeatureGrid";
import { SupportHeader } from "./SupportHeader";

export function PublicSupport() {
  return <main className="public-support">
    <SupportHeader active="plans" subtitle="Subscriber Support" />
    <section className="support-hero plans-first-hero" id="top"><div className="support-shell support-hero-grid"><div className="support-intro"><p className="eyebrow">LordsCare subscriptions & support</p><h1>Simple plans. Direct support. <em>No guesswork.</em></h1><p>Choose a plan for one to five managed accounts, see every price clearly, and send a prepared enquiry directly to LordsCare on WhatsApp.</p><div className="support-hero-actions"><Link className="primary-button support-cta" href="/plans">Compare subscription plans<CheckCircle2 /></Link><a className="support-plan-cta hero-whatsapp-cta" href={generalWhatsAppUrl} target="_blank" rel="noreferrer"><MessageCircle />Ask on WhatsApp</a></div><a className="hero-guide-link" href="#commands"><Command />Already subscribed? Browse the command guide</a></div><aside className="home-plans-card"><span className="home-plan-badge"><ShieldCheck />Clear published pricing</span><p>Plans start from</p><div className="home-plan-price"><small>₹</small><strong>150</strong><span>/ month</span></div><div className="home-plan-options"><span><strong>₹400</strong><small>3 months · 1 account</small></span><span><strong>₹1,500</strong><small>Yearly · 1 account</small></span></div><Link href="/plans">See all 15 plan options</Link></aside></div></section>
    <section className="support-highlights plan-highlights"><div className="support-shell"><div><ShieldCheck /><span><strong>Plans from ₹150/month</strong><small>Prices shown before you contact us</small></span></div><div><Users /><span><strong>Manage 1–5 accounts</strong><small>Choose only the capacity you need</small></span></div><div><MessageCircle /><span><strong>Direct WhatsApp enquiry</strong><small>A complete message is prepared for you</small></span></div></div></section>
    <section className="support-shell home-features-section"><header><div><p className="eyebrow">What LordsCare can handle</p><h2>Configure the tasks that matter to your account.</h2></div><p>From daily routines and protection to growth, army targets, gathering, Familiars, and guild tools.</p></header><FeatureGrid limit={6} compact /><div className="home-features-actions"><Link href="/features">Explore every feature</Link><Link href="/plans">Choose a plan</Link></div></section>
    <section className="support-shell home-how-section"><header><p className="eyebrow">Simple onboarding</p><h2>Three steps to get started</h2></header><div><article><span>01</span><h3>Choose your plan</h3><p>Select the number of accounts and your preferred subscription period.</p></article><article><span>02</span><h3>Tell us your priorities</h3><p>Choose the routines, protection rules, and development goals you need.</p></article><article><span>03</span><h3>Confirm your setup</h3><p>Continue directly with LordsCare through WhatsApp support.</p></article></div></section>
    <section className="support-shell home-conversion-card"><div><p className="eyebrow light">Ready to get started?</p><h2>Plans from ₹150 per month.</h2><p>Choose one to five managed accounts, compare monthly, three-month, and yearly prices, then send a prepared enquiry.</p></div><div><Link className="conversion-plans-link" href="/plans">Compare plans</Link><a className="conversion-whatsapp-link" href={generalWhatsAppUrl} target="_blank" rel="noreferrer"><MessageCircle />WhatsApp us</a></div></section>
    <section className="support-shell monster-home-promo"><div><p className="eyebrow light">Monster Hunt Guide</p><h2>Know the weakness. Send the right heroes.</h2><p>Search 43 verified monsters, compare attack recommendations, and open level-specific F2P and P2P lineups in seconds.</p><Link className="primary-button" href="/monsters"><Crosshair />Find a monster</Link></div><div className="monster-home-art" aria-hidden="true"><span /><span /><span /><strong>43 guides</strong></div></section>
    <section className="support-shell events-promo"><div><p className="eyebrow">Event guides</p><h2>Plan before you spend.</h2><p>Simple daily checklists, point sources, reward milestones, and preparation tips for major Lords Mobile events.</p><a className="secondary-button" href="/events">Explore event guides<CalendarDays size={17} /></a></div><a className="featured-event-card" href="/events#guild-duel"><span><Swords size={19} />First guide</span><strong>Guild Duel</strong><small>5 days · Daily themes · Solo and guild rewards</small></a></section>
    <div className="support-shell support-command-section" id="commands"><CommandLibrary prefix="!" /></div>
    <footer className="support-footer"><div className="support-shell"><div className="site-brand"><div className="brand-mark">LC</div><div><strong>LordsCare</strong><span>Bot subscriber support</span></div></div><p>Ready to enquire? <Link href="/plans">Compare plans</Link> or <a href={generalWhatsAppUrl} target="_blank" rel="noreferrer">chat with LordsCare on WhatsApp</a>.</p></div></footer>
  </main>;
}
